# Whenever this file is updated, you need to run misc/condalock.sh to create
# the environment.lock.yml file.
name: nd2tools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.8
  - conda-forge::tqdm
  - conda-forge::ruamel.yaml
  - conda-forge::importlib_resources
  - conda-forge::pims
  - imageio
  - matplotlib
  - pip
  - conda-forge::nd2reader
  - scikit-learn
  - imageio-ffmpeg
  - tqdm
  - pip:
      - matplotlib-scalebar
      - pyqt5
      - opencv-python
