# Whenever this file is updated, you need to run misc/condalock.sh to create
# the environment.lock.yml file.

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - conda-forge::tqdm
  - conda-forge::ruamel.yaml
  - conda-forge::importlib_resources
  - pims
  - imageio
  - matplotlib
  - pip
  - nd2reader=3.2
  - scikit-learn
  - scikit-image
  - imageio-ffmpeg
  - tqdm
  - time
  - seaborn
  - cv2
  - pip:
      - matplotlib-scalebar
      - pyqt5
      - opencv-python
