name: CI

on:
  pull_request:
  schedule:
    - cron: 0 7 * * 1,3,5
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  run:
    name: Run submodules
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Add conda to PATH
        if: runner.os == 'macOS'
        run: |
          sudo chown -R $USER /usr/local/miniconda/  # workaround for problem in macOS image
          echo ::add-path::$CONDA/condabin
      - name: Create Conda environment
        run: |
          conda info
          envfile=environment.$(echo ${{ runner.os }} | tr A-Z a-z | sed 's|macos|osx|').lock.yml
          conda env create -n testenv -f ${envfile}
          conda install -n testenv flake8 pytest
      - name: Run flake8
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          flake8 src/ tests/
          flake8 --select=W292 --filename '*.yaml,*.yml'
      - name: Run tests
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          pip install -e .
          pytest -v tests/
