name: Linux MacOS

on:
  pull_request:
  schedule:
    - cron: 0 7 * * 1,3,5
  push:
    paths-ignore:
      - 'figures/**'
      - 'README.md'

jobs:
  run:
    name: Setup and test nd2tools
    timeout-minutes: 10
    runs-on: {matrix.os}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          auto-update-conda: false
          environment-file: conda-linux-64.lock
      - name: Install nd2tools
        run: |
          conda activate testenv
          pip install .
          nd2tools --version
      - name: Install testing software
        run: |
          pip install flake8
          pip install pytest
      - name: flake8
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          flake8 src/ tests/
      - name: pytest
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          pip install -e .
          pytest -v tests/
